on: 
  #push:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: zolaton34/hello-world-docker-action@main
        with:
          who-to-greet: "${{ github.event.inputs.who-to-greet }}"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
